Controllers/FeedbackController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RateThePlate.Models;
using System.Text.RegularExpressions;

namespace RateThePlate.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly lannisterContext _context;


        public FeedbackController(lannisterContext context)
        {
            _context = context;
        }

        // getting all the feedback
        public async Task<IActionResult> Index()
        {
            //including badges and carplates
            var feedbacks = _context.Feedback.Include(f => f.Badge).Include(f => f.CarPlate);
            //getting all the feedback//show only one instance of carplate number
            var badgeCountViewModels = feedbacks.GroupBy(b => b.CarPlate).Select(f => new BadgeCountViewModel
            {
                Feedback = f.First(),
                Count = 0
            });
            // vaidation for search string
            ViewData["Pattern"] = "(([a-zA-Z]{2}.?)|(B.?[0-9]?))[0-9]{2}.?[a-zA-Z]{3}";

            return View(await badgeCountViewModels.ToListAsync());
        }

        // searching for car plate number
        public ActionResult Search(string searchString)
        {
            //removing unnecessary chars 
            searchString = Regex.Replace(searchString.ToUpper(), "[^0-9A-Z]", "");
            var result = new List<BadgeCountViewModel>();

            if (!String.IsNullOrEmpty(searchString))
            {
                // getting the feedbacks that have the car plate number like the search string
                var feedbacks = _context.Feedback.Where(s => s.CarPlate.PlateNumber.Equals(searchString))
                    .Include(f => f.Badge).Include(f => f.CarPlate).ToList();
                //getting feedbacks that have the same badge and  the badgecount number
                result = feedbacks.GroupBy(x => x.Badge).Select(y => new BadgeCountViewModel
                {
                    Feedback = y.First(),
                    Count = y.Count()
                }).ToList();
                if (result.Count <= 0)
                {
                    ViewData["Error"] = $"The car plate number: \"{searchString}\" was not found in our database!";
                }
            }

            return View("Index", result);
        }

    }
}

Controllers/RatePlateController.cs
using System;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using RateThePlate.Models;

namespace RateThePlate.Controllers
{
    public class RatePlateController : Controller
    {
        
        private const string apiKey = "2cc15131ee6341b59d3394ca6d4729d3";
        //setting a pattern for the plate number
        private Regex Pattern = new Regex(@"(([A-Z]{2}.?)|(B.?[0-9]?))[0-9]{2}[ ]?[A-Z]{3}");
        private readonly lannisterContext _context;

        public RatePlateController(lannisterContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        //uploadig image
        [HttpPost]
        public async Task<IActionResult> UploadImage(IFormFile file)
        {
            if (file == null)
            {
                return View("Error", new ErrorViewModel { RequestId = "Rate Plate" });
            }
            //getting the image
            ViewData["originalImage"] = FileToImgSrcString(file);
            var result = String.Empty;
            //connecting to the api
            using (var httpClient = new HttpClient())
            {
                string baseUri = "https://ratetheplate.cognitiveservices.azure.com/vision/v1.0/ocr";
                httpClient.BaseAddress = new Uri(baseUri);
                httpClient.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", apiKey);
                HttpContent content = new StreamContent(file.OpenReadStream());
                content.Headers.ContentType = new MediaTypeWithQualityHeaderValue("application/octet-stream");
                var response = await httpClient.PostAsync(baseUri, content);
                string jsonResponse = await response.Content.ReadAsStringAsync();
                var jresult = JObject.Parse(jsonResponse);
                
                //getting the string from the jresult
                foreach (var region in jresult["regions"])
                {
                    foreach (var line in region["lines"])
                    {
                        foreach (var word in line["words"])
                        {
                            result = result + " " + word["text"].ToString();
                        }
                    }
                }
            }
            //verifying if the result contains a valid plate number
            var finalResult = Pattern.Match(result).Value;
            var numberNotFound = finalResult.Equals(String.Empty);

            if (numberNotFound)
            {
                ViewData["Error"] = "No number found, please enter another image!";
            }
            else
            {
                ViewData["PlateNumber"] = Regex.Replace(finalResult, "[^0-9A-Z]", "");
            }

            ViewData["Badges"] = new SelectList(_context.Badge, "Id", "Rating");
            return View("Index");
        }

        //adding feedback to the database
        [HttpPost]
        public async Task<IActionResult> SubmitFeedback(FeedbackViewModel input)
        {
            //getting existing carplate from the database.
            var myCarPlate = await _context.CarPlate
                .FirstOrDefaultAsync(m => m.PlateNumber == input.PlateNumber);
            //if the carplate number is not in the database
            if (myCarPlate == null)
            {
                var carPlate = new CarPlate { PlateNumber = input.PlateNumber };
                _context.Add(carPlate);
                _context.SaveChanges();

                myCarPlate = await _context.CarPlate
                .FirstOrDefaultAsync(m => m.PlateNumber == carPlate.PlateNumber);
            }
            //getting the badge from the database
            var myBadge = await _context.Badge
                .FirstOrDefaultAsync(m => m.Id == input.BadgeId);
           
            //creating a new feedback 
            var feedback = new Feedback
            {
                BadgeId = myBadge.Id,
                CarPlateId = myCarPlate.Id,
                Created = DateTime.Now
            };

            //saving feedback to db
            _context.Add(feedback);
            await _context.SaveChangesAsync();

            ViewBag.Success = $"Thank you! Your feedback for number {feedback.CarPlate.PlateNumber} was added with Success!";

            return View("Index");
        }
        //image upload code
        private string BytesToSrcString(byte[] bytes)
        {
            return "data:image/jpg;base64," + Convert.ToBase64String(bytes);
        }

        private string FileToImgSrcString(IFormFile file)
        {
            byte[] fileBytes;

            using (var stream = file.OpenReadStream())
            {
                using (var memoryStream = new MemoryStream())
                {
                    stream.CopyTo(memoryStream);
                    fileBytes = memoryStream.ToArray();
                }
            }

            return BytesToSrcString(fileBytes);
        }

    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rate The Plate</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.js"></script>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar bg-primary navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" style="color:whitesmoke"  asp-controller="RatePlate" asp-action="Index" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" style="color:whitesmoke"  id="myNav"  asp-controller="Feedback" asp-action="Index">Search</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    @* changing rate the plate image *@
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Lannister Rate The Plate</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>*@
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>